name: secure_step
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  smooth_sheets: ^0.14.0
  get: ^4.7.2
  shake: ^3.0.0
  flutter_background_service: 5.1.0
  flutter_background_service_ios: ^5.0.3
  flutter_local_notifications: ^18.0.1
  vibration: ^3.1.3
  fluttertoast: ^8.2.12
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8
  family_bottom_sheet: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/landing_page/appLogo.svg
    - assets/landing_page/woman.jpg
    - assets/landing_page/shake.svg
    - assets/landing_page/hand.svg
    - assets/main_page/settings.svg
    - assets/main_page/contacts.svg
    - assets/main_page/avatar.svg
    - assets/main_page/shield.svg
    - assets/main_page/monitorON.svg
    - assets/main_page/monitorOFF.svg
    - assets/main_page/info.svg
    - assets/app_icon.png
    - assets/appIcon.png
    - assets/main_page/trackingIcon.svg
    - assets/main_page/enableTracking.svg
    - assets/main_page/locationPin.png
    - assets/profile_page/edit.svg
    - assets/profile_page/trash.svg
    - assets/profile_page/add.svg
    - assets/profile_page/empty.lottie
    - assets/profile_page/empty.json

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/appIcon.png"
